name: ShiftLeft

on:
  pull_request:
  workflow_dispatch:
  push:

    branches:
      - main
      - master
jobs:
  NextGen-Static-Analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: NextGen Static Analysis
      run: |
           ${GITHUB_WORKSPACE}/sl analyze --wait --app shiftleft-js-demo --tag branch=$"${{ github.head_ref || steps.extract_branch.outputs.branch }}" --js --cpg .
           ${GITHUB_WORKSPACE}/sl modify-findings --app shiftleft-js-demo
           ${GITHUB_WORKSPACE}/sl check-analysis --app shiftleft-js-demo --branch "${{ github.head_ref || steps.extract_branch.outputs.branch }}" --report --github-pr-number=${{github.event.number}} --github-pr-user=${{ github.repository_owner }} --github-pr-repo=${{ github.event.repository.name }}  --github-token=${{ secrets.GITHUB_TOKEN }}
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
